### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullName": "Motaleb Sabbir",
  "mobile": "01723189020",
  "password": "So@S2bb4r#",
  "role": "Volunteer"
}